### ISSUE TITLE
Could you please create "dev" branch? Because I want to fix some bugs.

### ISSUE THREAD

**Issue by Geson-anko** [mkrd/PathDict#1]
Hello, thanks for your great library "path-dict".
This library is what I wanted but I found 2 issues. 
So could you please create "dev" branch to safely send pull requests?

1st issue is that the __getitem__ method of PathDict can not use list type.
I want to use PathDict as following.

```python
from path_dict import PathDict
pd = PathDict()
pd["a/b/c".split("/")] = 0
```

2nd issue is that the PathDict doesn't return KeyError when the key does not exist.
This PathDict object returns None when it hasn't the key, but this specification is big problem. The reason is that None type can not be a value object.

The 2nd issue, however, must be considered carefully because it causes a major compatibility problem.

**Comment by mkrd** [comment]
@Geson-anko I created a dev branch!
About the 2nd issue, if a path is invalid, it should actually not return None, but an error. I'm gonna test that later

**Comment by mkrd** [comment]
Oh, sorry, you meant a valid but non-existent path. 
That behaviour is by design. This way you can access any path and then check if it contains something.
It only throws an error if you try to get a path value on a non-dict-like subcomponent.

**Comment by Geson-anko** [comment]
Thank you for creating "dev" branch! I'll send you pull requests right now!
I thought that we can ignore my 2nd issue by implementing `__contains__` method, so I'm going to implement it like below. 

```python
from path_dict import PathDIct
pd = PathDict()
pd["a","b"] = 1
print(["a"] in pd) # True
print(["a","b"] in pd) # True
print(["a","c"] in pd) # False
```

**Comment by mkrd** [comment]
@Geson-anko when you're done, just submit another PR. Also, please write a test for the __contains__ method.
When you're done, I will publish a new release!

**Comment by Geson-anko** [comment]
@mkrd  Thank you very much! I'm grad to contribute to `PathDict`! I just wrote the `__contains__` method and its tests, so I'll PR it right away!

**Comment by Geson-anko** [comment]
@mkrd I committed the correction to PR #3  according to your requests 5 days ago. Could you please let me know if there are still any other problems?

**Comment by mkrd** [comment]
@Geson-anko I'm currently still building a test pipeline, when it is finished, I will release the new build

**Comment by mkrd** [comment]
Done!
